apiVersion: batch/v1
kind: Job
metadata:
  name: download-models
spec:
  selector: {}
  template:
    spec:
      containers:
      - command:
        - /bin/bash
        - -ec
        - |-
          pip install huggingface_hub
          [[ -n ${INFERENCE_MODEL} ]] && huggingface-cli download --token ${HF_TOKEN} --local-dir=/cache/models/inference ${INFERENCE_MODEL}
          [[ -n ${SAFETY_MODEL} ]] && huggingface-cli download --token ${HF_TOKEN} --local-dir=/cache/models/safety ${SAFETY_MODEL}
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
          - secretRef:
              name: huggingface-secret
        image: registry.access.redhat.com/ubi9/python-39
        imagePullPolicy: IfNotPresent
        name: download-models
        volumeMounts:
          - mountPath: /cache/models
            name: models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models-cache
      restartPolicy: OnFailure
