apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
    openshift.io/display-name: llamastack-vllm-inference
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  creationTimestamp: "2025-04-04T10:41:40Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 8
  labels:
    opendatahub.io/dashboard: "true"
  name: llamastack-vllm-inference
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources: {}
      runtime: vllm-custom-runtime
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-1b-instruct
    tolerations:
    - effect: NoSchedule
      key: odh-notebook
      operator: Exists
