{{- $root := . }}
{{- range $.Values.inferenceServices }}
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .name }}
  annotations:
    openshift.io/display-name: {{ .name }}
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources: {}
      runtime: {{ .servingRuntime }}
      storageUri: {{ .storageUri }}
    {{- with $root.Values.acceleratorProfile.tolerations }}
    tolerations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
