{{- $root := . }}
{{- range $.Values.servingRuntimes }}
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: {{ .name }}
  annotations:
    opendatahub.io/accelerator-name: {{ $root.Values.acceleratorProfile.name }}
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '{{ printf "[%q]" $root.Values.acceleratorProfile.identifier }}'
    openshift.io/display-name: {{ .name }}
  labels:
    opendatahub.io/dashboard: "true"
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
  - args:
    - --port
    - "8000"
    - --max-model-len
    - "8192"
    - --model
    - /mnt/models
    {{- with .extraArgs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    command:
    - python3
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: VLLM_CONFIG_ROOT
      value: /vllm/config
    - name: VLLM_CACHE_ROOT
      value: /vllm/cache
    image: {{ .image }}
    name: kserve-container
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /vllm
      name: vllm-home
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 2Gi
    name: shm
  - emptyDir:
      sizeLimit: {{ .vllmVolumeSize }}
    name: vllm-home
{{- end }}
