apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: nvidia-gpu
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: rag-inference-vllm
  labels:
    opendatahub.io/dashboard: "true"
  name: rag-inference-vllm
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
  - args:
    - --enable-auto-tool-choice
    - --chat-template
    - /workspace/vllm/examples/tool_chat_template_llama3.2_json.jinja
    - --tool-call-parser
    - llama3_json
    - --port
    - "8000"
    - --max-model-len
    - "8192"
    - --model
    - /mnt/models
    command:
    - python3
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: VLLM_CONFIG_ROOT
      value: /vllm/config
    - name: VLLM_CACHE_ROOT
      value: /vllm/cache
    image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo@sha256:6b0d6af534a3c2a24fbcbd0e5e919f9f215be73fdf799a7bbd324178956cb7df
    name: kserve-container
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /vllm
      name: vllm-home
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 2Gi
    name: shm
  - emptyDir:
      sizeLimit: 5Gi
    name: vllm-home
