# Default values for rag-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/yuvalturg/llamastack-dist-ui
  pullPolicy: IfNotPresent
  tag: 0.1.9

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8501

env:
  - name: LLAMA_STACK_ENDPOINT
    value: 'http://llamastack:8321'

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

global:
  models:
    inference:
      id: meta-llama/Llama-3.2-3B-Instruct
      storageUri: oci://quay.io/yuvalturg/modelcars:llama-3.2-3b-instruct
      serviceName: rag-inference
      args:
      - --enable-auto-tool-choice
      - --chat-template
      - /vllm-workspace/examples/tool_chat_template_llama3.2_json.jinja
      - --tool-call-parser
      - llama3_json
    safety:
      id: meta-llama/Llama-Guard-3-8B
      storageUri: oci://quay.io/yuvalturg/modelcars:llama-guard-3-8b
      serviceName: rag-safety

llm-service:
  servingRuntimeImage: docker.io/vllm/vllm-openai@sha256:4d8d397a62c36237293a4d5e2acbf911b91b0a8552825bda69f581c5811af9ec


## llama-serve and safety-model were replaced by llm-service, set replicaCount=0 ##
llama-serve:
  replicaCount: 0
  extraArgs:
    - --model
    - meta-llama/Llama-3.2-3B-Instruct
  tolerations:
    - effect: NoSchedule
      key: g6e-gpu
      value: 'true'
  resources:
    limits:
      nvidia.com/gpu: "1"
  image:
    repository: vllm/vllm-openai
    pullPolicy: IfNotPresent
    tag: latest

safety-model:
  replicaCount: 0
  extraArgs:
    - --model
    - meta-llama/Llama-Guard-3-8B
  tolerations:
    - effect: NoSchedule
      key: odh-notebook
      value: 'true'
  resources:
    limits:
      nvidia.com/gpu: "1"
  image:
    repository: vllm/vllm-openai
    pullPolicy: IfNotPresent
    tag: latest
